blank_issues_enabled: false
contact_links:
  - name: ðŸ¤” Have questions or need support?
    url: https://discord.gg/WzhxEY62mB
    about: Discuss with us on Discord
  - name: ðŸ¤” Have questions or need support?
    url: https://github.com/hoylabs/OpenDTU-OnBattery/discussions
    about: Use the GitHub Discussions feature
